version: '3.1'

services:

  mongo:
      build:
        context: ./
        dockerfile: dockerfile
      image: mongo
      container_name: teste
      restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_SERVER=teste
